title: Federico Bonafini
author: Federico Bonafini
theme: minima

minima:
  # social_links:
  #   github: FedericoBonafini
  navigation:
    - title: "Home"
      url: "/"
    - title: "Publications"
      url: "/publications/"
    - title: "CV"
      url: "/cv/"
