<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

title: Federico Bonafini
author: Federico Bonafini
theme: minima

minima:
  # social_links:
  #   github: FedericoBonafini
  navigation:
    - title: "Publications"
      url: "/publications/"
    - title: "CV"
      url: "/cv/"
    - title: "Teaching"
      url: "/teaching/"
