title: Federico Bonafini
author: Federico Bonafini
theme: minima

minima:
  navigation:
    - title: "About"
      url: "/"
    - title: "Publications"
      url: "/publications/"
    - title: "CV"
      url: "/cv/"
    - title: "Teaching"
      url: "/teaching/"
